apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-notifications
  namespace: microtodo
spec:
  serviceName: postgres-notifications-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-notifications
  template:
    metadata:
      labels:
        app: postgres-notifications
    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
      - name: init-chown-data
        image: busybox:1.36
        securityContext:
          runAsUser: 0
        command: ["sh","-lc"]
        args:
          - |
            mkdir -p /var/lib/postgresql/data/pgdata && chown -R 999:999 /var/lib/postgresql/data
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:15
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: notifications_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: microtodo-secrets
              key: postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microtodo-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      storageClassName: gp3
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notifications-service
  namespace: microtodo
spec:
  selector:
    app: postgres-notifications
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
