apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-tasks
  namespace: microtodo
spec:
  serviceName: postgres-tasks-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres-tasks
  template:
    metadata:
      labels:
        app: postgres-tasks
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: tasks_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: microtodo-secrets
              key: postgres-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microtodo-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tasks-service
  namespace: microtodo
spec:
  selector:
    app: postgres-tasks
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
