apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microtodo-secrets
  namespace: microtodo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: microtodo-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-username
    remoteRef:
      key: microtodo/secrets
      property: postgres-username
  - secretKey: postgres-password
    remoteRef:
      key: microtodo/secrets
      property: postgres-password
  - secretKey: rabbitmq-username
    remoteRef:
      key: microtodo/secrets
      property: rabbitmq-username
  - secretKey: rabbitmq-password
    remoteRef:
      key: microtodo/secrets
      property: rabbitmq-password
  - secretKey: jwt-access-secret
    remoteRef:
      key: microtodo/secrets
      property: jwt-access-secret
