apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microtodo-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/microtodo/infrastructure
    targetRevision: master
    path: k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: microtodo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
